configuration: Release

before_build:
  - nuget restore Nine.Imaging.sln

build:
  parallel: true
  publish_nuget: true

version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

deploy:
- provider: NuGet
  api_key:
    secure: /Aez/maYDiX55BgGX9EkbhXBaBySsfdKifgB9SZxqySOrwtMVgPf7jOwS2XwKYJR
  skip_symbols: true
  on:
    branch: master