os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
  DNX_FEED: https://www.nuget.org/api/v2
install:
  - dnvm install 1.0.0-beta5
  - dnu restore
  - dnu pack src/Nine.Injection --configuration Release --out artifacts
  - cd test\Nine.Imaging.Test
  - dnx . test
build: off
artifacts:
  - path: artifacts\**\*.nupkg
